// <auto-generated />
using System;
using AcademiaPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademiaPro.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240819155249_ChangeSortOrderTypeFromByteToInteger")]
    partial class ChangeSortOrderTypeFromByteToInteger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sms_app")
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("AcademiaPro.Domain.Entities.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("LevelId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes", "sms_app");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8193),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8229),
                            Name = "Class 1",
                            SortOrder = 1
                        },
                        new
                        {
                            LevelId = 2,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8232),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8233),
                            Name = "Class 2",
                            SortOrder = 2
                        },
                        new
                        {
                            LevelId = 3,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8234),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8235),
                            Name = "Class 3",
                            SortOrder = 3
                        },
                        new
                        {
                            LevelId = 4,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8236),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8237),
                            Name = "Class 4",
                            SortOrder = 4
                        },
                        new
                        {
                            LevelId = 5,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8239),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8240),
                            Name = "Class 5",
                            SortOrder = 5
                        },
                        new
                        {
                            LevelId = 6,
                            CreatedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8241),
                            LastModifiedAt = new DateTime(2024, 8, 19, 16, 52, 49, 66, DateTimeKind.Local).AddTicks(8256),
                            Name = "Class 6",
                            SortOrder = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
