// <auto-generated />
using System;
using AcademiaPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcademiaPro.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240816044004_AddLevelTableSeedDataInTo")]
    partial class AddLevelTableSeedDataInTo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sms_app")
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("AcademiaPro.Domain.Entities.Level", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("LevelId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("smallint");

                    b.HasKey("LevelId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Classes", "sms_app");

                    b.HasData(
                        new
                        {
                            LevelId = 1,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6432),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6445),
                            Name = "Class 1",
                            SortOrder = (byte)1
                        },
                        new
                        {
                            LevelId = 2,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6447),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6448),
                            Name = "Class 2",
                            SortOrder = (byte)2
                        },
                        new
                        {
                            LevelId = 3,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6449),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6449),
                            Name = "Class 3",
                            SortOrder = (byte)3
                        },
                        new
                        {
                            LevelId = 4,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6450),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6450),
                            Name = "Class 4",
                            SortOrder = (byte)4
                        },
                        new
                        {
                            LevelId = 5,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6451),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6452),
                            Name = "Class 5",
                            SortOrder = (byte)5
                        },
                        new
                        {
                            LevelId = 6,
                            CreatedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6452),
                            LastModifiedAt = new DateTime(2024, 8, 16, 5, 40, 4, 325, DateTimeKind.Local).AddTicks(6460),
                            Name = "Class 6",
                            SortOrder = (byte)6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
